KG-51-game-design-without-ui
tivelabs/hangedman-game pull request #1
Opened 2022-12-28 15:33 UTC by natalyTive

2022-12-29 19:59 UTC, marcelotivelabs requested changes

2022-12-29 19:59 UTC, marcelotivelabs commented on src/data/animals_english.js
> +      level: 'Hard',
That means that when other data needs to be used, a person must pre process the data and classify it, and that person can classify a long word at a low level or at another level.
But, the application can classify the data according to the length of the words for example, and thus the levels would not necessarily be in the data.

2023-01-03 23:31 UTC, marcelotivelabs requested changes

2023-01-03 23:31 UTC, marcelotivelabs commented on index.js
> +export function initHangedMan(category, level) {
Please add some validations for the function's incoming parameters.

2023-01-06 09:29 UTC, vbrianh requested changes

2023-01-06 09:29 UTC, vbrianh commented on src/util/arrayUtils.js
> +        myArray.forEach(e => {
remove unnecessary variable e, example use _

2023-01-06 09:29 UTC, vbrianh commented on src/util/arrayUtils.js
> +            case 'Animals':
move to constants, example

const categories = {
    animals: 'Animals',
    numbers: 'Numbers',
};

case categories.animals

2023-01-06 09:29 UTC, vbrianh commented on test/util/hangedManUtils.test.js
> +import hangedManUtils from "../../src/util/hangedManUtils";
i have the next error 
![Screenshot 2023-01-06 at 05 27 57](https://user-images.githubusercontent.com/117357295/210972042-e86945d8-3551-44a5-83cc-357c0ded895d.png)

2023-01-10 05:07 UTC, vbrianh approved these changes
LGTM!

2024-06-28 09:29 UTC, tiveor approved these changes
LGTM

2024-06-28 09:29 UTC, merged